Nike-Inc/hal

src/AWS/Lambda/Runtime.hs

Should look nice when run through haddock :)
Hard to be positive that these are 100% accurate, being in the docs and all, but I was pretty thorough.  I added all the imports explicitly because I always find it a challenge in documentation examples when I don't know where key things come from.  Wanted the examples to be something that you could copy into a file and have work immediately.

Add detailed documentation/examples for each exported runtime.

---

stack.yaml

It turns out that without that flag we will set bounds on our packages
that will break on newer LTS versions. Rather than risk having `hal`
removed from Stackage for versions that are _likely_ fine, we'll enable
this flag and add more LTS versions to Travis builds when they're
working :)
Once this is merged I'll cut another bug fix release and re-submit to Stackage.

Bump LTS minor version and add revision to PVP bounds

---

src/AWS/Lambda/RuntimeClient.hs

This is just a good idea in general, allows much longer retry windows without risking over consumption of resources (potentially blocking the AWS runtime from doing what it needs to do).
This also should eliminate the final visible lingering effects of #54 given that the retry window is so much longer.
Solves #59

Add exponential backoff on retries and retry for up to one second.

---

package.yaml
src/AWS/Lambda/Runtime.hs
src/AWS/Lambda/RuntimeClient.hs

This is a precursor to enabling a custom HTTP manager.  This refactor helps hide internal details of the runtime client, so that additions (such as the manager) can be made transparently to the consuming modules, making diffs smaller and backporting easier.
This is really just a start to the opportunities here (more hiding, monadic interfaces, etc), but it's a step in the right direction.

Hide base runtime request in config

---

package.yaml
src/AWS/Lambda/RuntimeClient.hs

HTTP Simple uses a global immutable manager with a 30s request timeout.  This makes good sense for a simple interface with sensible defaults, but timeouts don't make sense in a lambda context (the container will be frozen indefinitely) and causes unneeded churn and errors.
We also add some other reasonable manager settings like no proxy to prevent incorrect behavior based on global config and limiting maximum connections to ensure re-use and a light footprint.

Use an explicit manager to eliminate request timeouts

---

.gitignore
hal.cabal

Please consider removing *.cabal from .gitignore to allow cabal projects being able to use `hal`.
For context, I'm currently migrating a project that uses hal from stack to cabal. Currently cabal can't build the project because of the missing cabal file and once the build fails, I have to manually go into hal's work dir and run hpack to generate hal.cabal from package.yaml so that the build can continue.

Remove *.cabal from .gitignore

---

README.md

Based on issues identified in #78.  This at least steers someone in the right direction, even if it doesn't offer much in solving builds/sam.

Update README to reflect current local testing and building considerations

---

hal.cabal
package.yaml
src/AWS/Lambda/RuntimeClient.hs

…, as it was only providing simple helpers.
Notably, this drops `cryptonite` which is a bit more work to build in newer versions for lambda.  This doesn't save anyone who truly needs it (essentially users of HTTPS), but it at least simplifies builds for those who don't.

Drop http-conduit as a dependency

---

src/AWS/Lambda/RuntimeClient/Internal.hs
test/Spec.hs

Error itself is quite vague in these cases, and this notably does happen when you try to use sam local, so clearer errors here help might help steer people in the right direction.  Partly came out of discussion in #78.

Add more detailed error messages on Context failure

---

.github/workflows/haskell_cabal.yaml

Not sure if this will actually work, but if we can keep around the older GHC versions this easily that would be nice.

Use newer cabal version since support has been dropped.

---

.github/workflows/haskell_stack.yaml
hal.cabal
package.yaml
src/AWS/Lambda/Context.hs
src/AWS/Lambda/Internal.hs
src/AWS/Lambda/RuntimeClient.hs

Envy is a pretty handy library that does some pretty cool things--however, it's got a bit of churn in its versioning, and we really don't use _that_ much from it.  It makes more sense to simply replace the functionality so that broad support of LTSes is simpler.

Reduce envy usage for greater compatibility

---

hal.cabal
package.yaml

This'll make it show up as a change log on future hackage releases.

hal.cabal: Add CHANGELOG.md to extra-source-files

---

CHANGELOG.md
hal.cabal
package.yaml
src/AWS/Lambda/Events/Kafka.hs
test/AWS/Lambda/Events/ApiGateway/ProxyRequest/Gen.hs
test/AWS/Lambda/Events/ApiGateway/ProxyRequest/Spec.hs
test/AWS/Lambda/Events/ApiGateway/ProxyResponse/Spec.hs
test/AWS/Lambda/Events/Kafka/Gen.hs
test/AWS/Lambda/Events/Kafka/Spec.hs
test/Spec.hs

We've been using this internally for a few weeks now so it's probably worth thinking about upstreaming it.
Haven't done a package version bump and I expect many stack CIs to fail - we'll need to relax bounds once we know what the different LTSes want.
I also want to double-check that MSK event mappings provide a list of bootstrap brokers. The docs don't mention this but I'm pretty sure they did when I had a test cluster running.
Also: What else do we want to get into the next version? I'm happy to do up a PR for a default exception handler, and with `envy` still depending on `bytestring == 0.10.*` (and not having been updated for nearly a year), maybe we should prune it to remove a blocker on GHC9 support?

Kafka event mapping

---

.github/workflows/haskell_cabal.yaml

I'll put this back later if I can, but notably we don't support stack back this far anyway (would be LTS 9).  Current builds fail based on this issue here: https://github.com/haskell-foundation/foundation/issues/561.

Drop Cabal GHC 8.0.2 support.

---

hal.cabal
package.yaml

Want to get this in before 0.4.9 to avoid a revision later.

Relax hedgehog upperbounds to include 1.1

---

CHANGELOG.md
src/AWS/Lambda/RuntimeClient.hs

Fixes #100.  After discussion there, logging errors appear to be standard practice in custom runtimes, and doesn't pose any risks of leaking information than is already present (returning errors to the invoking entity seems much more concerning, and that always happens regardless).
There's no standard or recommendation across runtimes, so this aims to just fit in nicely to other AWS Lambda standard messaging.  This should be parse-able in a similar way:  all caps tag followed by key value pairs separated by tabs (only `Message` will be present today, but that lets us extend later).  Since users may parse this data, its format likely needs to be considered under contract.

Feature: log on invoke error

---

CHANGELOG.md
src/AWS/Lambda/Events/EventBridge/Detail/SSM/ParameterStoreChange.hs

I forgot to fix the changelog when I moved the `ParameterStoreChange` module under `Detail`. While it's not worth another release, the changelog can at least be correct in future versions.

CHANGELOG.md: correct module name

---

.github/workflows/haskell_cabal.yaml
.github/workflows/haskell_stack.yaml
hal.cabal
package.yaml
src/AWS/Lambda/Events/ApiGateway/ProxyRequest.hs
stack-lts-18.yaml
stack-lts-19.yaml

Stack LTS 18 and LTS 19 and GHC 9.0, 9.2, and 9.4 with Cabal.
Fixes #114

Extend supported versions to newer versions of GHC

---

.github/workflows/haskell_cabal.yaml
.github/workflows/haskell_stack.yaml
stack-lts-20.yaml

Our GIthub action can no longer install GHC 8.2.2, so this is causing false negatives.  Long term, i'd like to explore using something like nix to address this.
While here, we add support for stack LTS 20.  LTS 21 involves extending test dependency constraints, which currently is going to cause some merge conflict noise.

Drop 8.2.2 for Cabal add lts 20

---

CHANGELOG.md
hal.cabal
package.yaml
src/AWS/Lambda/Events/Kafka.hs

Do not merge until `attoparsec-aeson` has a compat package on Hackage

Add support for aeson 2.2

---

hal.cabal
package.yaml

This lets the current version play nicely with the current stack LTS (and next if the flag is changed), and lets cabal users get the benefits of either automatically.  In the next breaking change release, we can flip the default.

Set default use of Aeson 2.2 to false.
